"""Init Revision

Revision ID: e3c1f6a5d0c2
Revises: 
Create Date: 2025-04-30 10:39:34.168162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3c1f6a5d0c2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('need_to_scrape', sa.Boolean(), nullable=True),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='metadata'
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='metadata'
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='metadata'
    )
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='metadata'
    )
    op.create_table('unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='metadata'
    )
    op.create_table('products_input_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('upload_on_pr', sa.Boolean(), nullable=True),
    sa.Column('input_currency_id', sa.Integer(), nullable=False),
    sa.Column('input_unit_id', sa.Integer(), nullable=False),
    sa.Column('expected_unit_id', sa.Integer(), nullable=False),
    sa.Column('input_quantity', sa.DECIMAL(precision=18, scale=4), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['expected_unit_id'], ['metadata.unit.id'], ),
    sa.ForeignKeyConstraint(['input_currency_id'], ['metadata.currency.id'], ),
    sa.ForeignKeyConstraint(['input_unit_id'], ['metadata.unit.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['metadata.location.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['metadata.product.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['metadata.source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'product_id', 'input_unit_id', 'location_id', name='uq_source_product_unit_location'),
    schema='input'
    )
    op.create_table('exchange_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('from_currency_id', sa.Integer(), nullable=False),
    sa.Column('to_currency_id', sa.Integer(), nullable=False),
    sa.Column('average_rate', sa.Float(), nullable=False),
    sa.Column('min_rate', sa.Float(), nullable=True),
    sa.Column('max_rate', sa.Float(), nullable=True),
    sa.Column('last_update', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['from_currency_id'], ['metadata.currency.id'], ),
    sa.ForeignKeyConstraint(['to_currency_id'], ['metadata.currency.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'from_currency_id', 'to_currency_id', name='uq_exchange_date_pair'),
    schema='metadata'
    )
    op.create_table('unit_conversion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('base_unit_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('conversion_factor', sa.Float(), nullable=False),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['base_unit_id'], ['metadata.unit.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['metadata.unit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='metadata'
    )
    op.create_table('web_config',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['metadata.source.id'], ),
    sa.PrimaryKeyConstraint('source_id'),
    schema='metadata'
    )
    op.create_table('products_raw_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('product_config_id', sa.Integer(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('price_value', sa.DECIMAL(precision=18, scale=4), nullable=False),
    sa.Column('product_category', sa.String(length=100), nullable=True),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_config_id'], ['input.products_input_data.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['metadata.source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'price_date', 'product_config_id', name='uq_raw_source_product_config'),
    schema='raw_data'
    )
    op.create_table('products_standard_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.DECIMAL(precision=18, scale=4), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('price_usd', sa.DECIMAL(precision=18, scale=4), nullable=False),
    sa.Column('source_date', sa.Date(), nullable=False),
    sa.Column('raw_data_id', sa.Integer(), nullable=True),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['metadata.location.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['metadata.product.id'], ),
    sa.ForeignKeyConstraint(['raw_data_id'], ['raw_data.products_raw_data.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['metadata.source.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['metadata.unit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'product_id', 'location_id', 'source_date', name='uq_std_source_product_location_date'),
    schema='transformed'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products_standard_data', schema='transformed')
    op.drop_table('products_raw_data', schema='raw_data')
    op.drop_table('web_config', schema='metadata')
    op.drop_table('unit_conversion', schema='metadata')
    op.drop_table('exchange_rate', schema='metadata')
    op.drop_table('products_input_data', schema='input')
    op.drop_table('unit', schema='metadata')
    op.drop_table('source', schema='metadata')
    op.drop_table('product', schema='metadata')
    op.drop_table('location', schema='metadata')
    op.drop_table('currency', schema='metadata')
    # ### end Alembic commands ###
