# Dockerfile
FROM python:3.11-slim

WORKDIR /app

COPY requirements.api.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY api_server/ api_server/
COPY db/ db/
COPY utility/ utility/
COPY .env .

CMD ["uvicorn", "api_server.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
