"""Initial schema setup

Revision ID: 2f083f667b95
Revises: 
Create Date: 2025-04-21 10:19:20.176871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f083f667b95'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='metadata'
    )
    op.create_table('location',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('name'),
    schema='metadata'
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='metadata'
    )
    op.create_table('unit',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='metadata'
    )
    op.create_table('products_input_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('expected_currency_code', sa.String(length=10), nullable=False),
    sa.Column('expected_unit_code', sa.String(length=50), nullable=False),
    sa.Column('expected_quantity', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('location_id', sa.String(length=50), nullable=True),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['expected_currency_code'], ['metadata.currency.code'], ),
    sa.ForeignKeyConstraint(['expected_unit_code'], ['metadata.unit.code'], ),
    sa.ForeignKeyConstraint(['location_id'], ['metadata.location.name'], ),
    sa.ForeignKeyConstraint(['product_id'], ['metadata.product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name', 'product_id', 'expected_unit_code', 'location_id', name='uq_source_product_unit_location'),
    schema='input'
    )
    op.create_table('products_transformed_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('unit_code', sa.String(length=50), nullable=True),
    sa.Column('price_usd', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('source_date', sa.Date(), nullable=False),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['metadata.location.name'], ),
    sa.ForeignKeyConstraint(['product_id'], ['metadata.product.id'], ),
    sa.ForeignKeyConstraint(['unit_code'], ['metadata.unit.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name', 'product_id', 'location_id', 'source_date', name='uq_std_source_product_location_date'),
    schema='transformed'
    )
    op.create_table('products_raw_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('price_value', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('product_category', sa.String(length=100), nullable=True),
    sa.Column('product_config_id', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_config_id'], ['input.products_input_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name', 'price_date', 'product_config_id', name='uq_raw_website_date_config'),
    schema='raw_data'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products_raw_data', schema='raw_data')
    op.drop_table('products_transformed_data', schema='transformed')
    op.drop_table('products_input_data', schema='input')
    op.drop_table('unit', schema='metadata')
    op.drop_table('product', schema='metadata')
    op.drop_table('location', schema='metadata')
    op.drop_table('currency', schema='metadata')
    # ### end Alembic commands ###
