name: "sunsirs_monitor"
start_date: '2025-01-01'
base_url: "https://www.sunsirs.com/uk/sdetail-day-REPLACEDATEHERE.html"
required_headers : ["Commodity", "Sectors"]

llm_task: extract_commodity_units
model: deepseek-r1-distill-llama-70b
prompt_template: |
  You are a strict JSON API that extracts commodity pricing information from semi-structured remarks.

  Instructions:
  1. Extract the default price/weight unit from the text if declared.
  2. For each commodity:
     - Use its own unit if present.
     - Otherwise, fall back to the default.
  3. Respond only with valid JSON using this format:

  {{schema}}

  Input:
  "{{input}}"